//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class suic_capacitacion
    {
        public int id_suic { get; set; }
        public string rom { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
