//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class suic
    {
        public int id_suic { get; set; }
        public string rom { get; set; }
        public string placa { get; set; }
        public string nit_centro_informacion { get; set; }
        public string nit_taller_conversion { get; set; }
        public string nit_empresa_certificadora { get; set; }
        public System.DateTime fecha_certificacion_inicial { get; set; }
        public System.DateTime fecha_ultima_revision { get; set; }
        public System.DateTime fecha_proxima_revision { get; set; }
        public Nullable<System.DateTime> fecha_proxima_revision_quinquenal { get; set; }
        public bool habilitado { get; set; }
        public string ciudad_dane { get; set; }
        public string cedula_inspector_certificador { get; set; }
        public Nullable<int> id_vehiculo { get; set; }
        public Nullable<int> id_entidad_cliente { get; set; }
        public Nullable<int> id_tipo_documento { get; set; }
        public string documento { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
    }
}
